[config]
model = "glm-4-flash"
git_provider = "github"

[openai]
api_base = "https://open.bigmodel.cn/api/paas/v4/"
api_type = "azure"

[pr_reviewer]
auto_review = true
require_security_review = true
num_code_suggestions = 4
inline_code_comments = true